apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgCq3jlb0ncSP8WdHF89+q7QdDdfLQY2EAHky1VlBvuyR0oWvgujkl78TovwxU9tpJ8UN+hwIb/1CfEwwmOF3WEDkwVZblMlG0uGdLOMcHSGkrs96s/hVUqZ/Q6KXkhIdIBIMqIKILZWoBwyszWA2iooNSahimJt6+MAnHhwVu9yv6Yk2OlkD5uCQXeH1ChnM1NRzIXh3NcN7X7f10C5ZnyREHYW6Ls71X6BxB3n+ELopev3ZpQYWDweTvqftm1JX3Z5tn06c/cyaralPBn/eNonnx1u0a9aaDisUW2hGxGMQLPN4QXO3n2Mxz8+53htQt3h1m9qPih9pasZu7IdYDO75NMbx/k1+QtRku+hWJlNOkZcsQYHFW06Az6z/+QItyQKAk2/dxkuB76CoybQN1gX3XWA1mjMSdTJQIMaO/7bhKgGOIMuSnV1BYYVYSIsgmf8CjFE9ao/n0dIxm+KabmA39rUouEOF9wMIO11gfNuDjgPDwWFMFjE6UbRV25QSaos/BthJCkAlN4Mqr8HAeBiNn8/sd1Oue+SXzKxdJR4ZmLWL1ne/T105eOXngQyXQfy77bF3vS6VxbJjA6pu85yb83MiedSR7EH4pQPNSZ3uDoDqABn1Hme//aoXnhra5KjwkTNwDFiOggZLqpTO5cctLGp31YEcH74izHeVSyJ3FcyjSb3/kyCwu8FlaEpS5HnDR4DEqE9mY4qQEeXH0ogDmu1PkfmSNqS
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

