apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:zNE75XMiZBzJy6vIlomFH1ydaZ8v3CRCUA==,iv:Ab48NuaOJ4sGxcbr4xJf8LSDEN7uKEuPWq/aDG0leUc=,tag:Y6WdSVE65spQtrpf+GBp0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-08-12T16:24:01Z"
    mac: ENC[AES256_GCM,data:iSVG30EU+4yDbE4yFhFPdZ0LEILGNoTobJMo6cNSZe2iOrnh+1qw01hyY5JeJCH3ICPr4i2SDYprt2H5kzfvzbbkiExa2c9jdLXB2U6h343VIHfy/wjLci2JMpyskCOW3fYesRf7EVBt1l455Mxge2qYUF6ePS7tFVjEa5RNdbc=,iv:SnGQ8cH/vtUxICtlh5j1ajwyjpX0pfN9YwKngUrQjI8=,tag:UqdLO9al7BY/D8VBybXI8Q==,type:str]
    pgp:
        - created_at: "2025-08-12T16:24:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAwjvvs3ofZsWAQv/Z0omqBJaWxEkBnxGogD4LQZOaAebxxNsW5K/OC7o/Y3e
            u50adbvf+/xXmkreOBMTfAHon7aQdlxTwnVV3uYqFzPjsHLUW1+0hjjO+Q6mCqnZ
            S2vfFtC1+M9oSC/86VRWTshfn2uSb9VC7Q/naWm3znWX19jkUIZFcfIgUdWY4jR4
            qExUONm2DUNLw8DBHmi2IuJhRWvBBpxl1ywhJs8p2CSSrOmYULMqfhpoSm9rE1rV
            ohycq/cPsNEQmcAv/Mc1krh9NaxVYt5RYqaEUOR3m5UfZswpO4HO7MP0gWqg2aVc
            MJgRqKPw1wcbvDfALCoAUdZ5ao4dveOi+AtZlSEX4E+OJJBAv6pk/0tc2/gUiuSL
            n2BT3e5CISdUR+kcuoa9cFWCWhQmrPZ2DMbCZ01gplLm0MT7lyhVs7dtK12VfKRi
            VWaNy/HBdQvhRSmve3ObVf6AUPs0YBM/D8uJqLiV08s2Ad2kcXKjRI6rtSYA8YWB
            H+bF570W5UnsICJDIVPx1GgBCQIQvcWyqVGl63rXyEgbzh0WedZfm+cb29Qn05Ak
            qTZioO2IYGG8foPlzSbd2KO4B8lYBQLza9kT8b51dI6kM9RJZBI7r6K1Ne7jyilv
            9g+hWVRu0r9eWPy2tC04T8yGkU2+A/AQcw==
            =xb6c
            -----END PGP MESSAGE-----
          fp: 095D89D134A82FA0C9EEA9CB7E5C1E8F8AA29FB8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
